language: php

dist: trusty

sudo: false

addons:
  apt_packages:
    - enchant

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - TEST_COMMAND="composer test"

branches:
  except:
    - /^analysis-.*$/
    - /^flintci-.*$/

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" TEST_COMMAND="composer test"

install:
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - pip install --user -r doc/requirements.txt

script:
  - $TEST_COMMAND