language: php

dist: trusty

sudo: false

addons:
  apt_packages:
    - enchant

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - TEST_COMMAND="composer test"

branches:
  except:
    - /^analysis-.*$/
    - /^flintci-.*$/

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" TEST_COMMAND="composer test"

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - $TEST_COMMAND